controller_manager:
  ros__parameters:
    update_rate: 6

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - elbow_joint
      - arm_joint
      - grip_joint
      - gripper_joint
      - endeffector_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 20.0
    action_monitor_rate: 10.0
    allow_partial_joints_goal: false
