closetbot_controller:
  ros__parameters:
    update_rate: 6
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - shoulder_joint
      - elbow_joint
      - arm_joint
      - grip_joint
      - gripper_joint
      - endeffector_joint
    write_op_modes:
      - shoulder_joint
      - elbow_joint
      - arm_joint
      - grip_joint
      - gripper_joint
      - endeffector_joint
    state_publish_rate: 25
    action_monitor_rate: 20

joint_state_controller:
  ros__parameters:
    update_rate: 6
    type: joint_state_controller/JointStateController
    publish_rate: 50